const drizlyNames = ["Crown Royal Fine Deluxe Blended Canadian Whisky 375ml Bottle", 
"Bulleit Bourbon Whiskey Bottle with Two Branded Ceramic Mugs 750ml Bottle", 
"Popov Vodka 100 375ml Plastic Bottle", 
"Popov Vodka 80 200ml Bottle", 
"Smirnoff No. 57 100 Proof Vodka 750ml Bottle", 
"Smirnoff No. 21 Vodka 750ml Bottle", 
"E&J VS Brandy 375ml Bottle", 
"E&J VS Brandy 200ml Bottle", 
"E&J VS Brandy 1.75L Bottle", 
"E&J VS Brandy 750ml Bottle", 
"BOMBAY SAPPHIRE® Gin 200ml Bottle", 
"Corona Hard Seltzer Limonada Gluten Free Original Variety Pack Spiked Sparkling Water 12x 12oz Cans", 
"Cutwater Cucumber Vodka Soda 12oz Can", 
"Chivas Regal 18 Year 750ml Bottle", 
"Tres Generaciones Plata Tequila 750ml Bottle", 
"New Amsterdam Gin 1.75L Bottle", 
"The Balvenie 17 Year Old DoubleWood Single Malt Scotch Whisky 750ml Bottle", 
"Doritos Cool Ranch 9.25oz Bag", 
"Ciroc Vodka 375ml Bottle", 
"Ballast Point Big Gus IPA 6x 12oz Cans", 
"Deep Eddy Vodka 750ml Bottle", 
"Maker's Mark Wood Finishing Series Limited Release 750ml Bottle 2019", 
"Maker's Mark 101 Bourbon Whisky 750ml Bottle", 
"Corazon Reposado Tequila 750ml Bottle", 
"Cheez-It Extra Toasty Snack Crackers 12.4oz Bag", 
"J&B Rare Blended Scotch 200ml Bottle", 
"Camarena Reposado 50ml Bottle", 
"Topo Chico Hard Seltzer Variety Pack 12x 12oz Cans", 
"Gallo Family Vineyards Valley Moscato 750ml Bottle", 
"White Claw Watermelon Hard Seltzer 6x 12oz Cans", 
"Hess Allomi Cabernet Sauvignon 750ml Bottle", 
"Carta Blanca 32oz Bottle", 
"1800 Ultimate Spicy Margarita 1.75L Bottle", 
"Pepperwood Grove Pinot Grigio 750ml Bottle", 
"Mr & Mrs T Strawberry Daiquiri-Margarita Mix 1L Bottle", 
"G Fuel Sour Blue Chug Rug Energy Drink 10.4oz Can", 
"Estancia Pinot Noir 750ml Bottle", 
"Tree House Brewing Eureka Blonde Ale 16oz Can", 
"Snickers Bar Peanut Butter 1.4oz Count", 
"Cutwater Tequila Margarita 4x 12oz Cans", 
"El Jimador Reposado Tequila 50ml Bottle", 
"Boochcraft Strawberry Lemonade 16oz Can", 
"Fernet-Branca 50ml Bottle", 
"Mr. & Mrs. T Original Bloody Mary Mix 1L Bottle", 
"Barefoot Refresh Sweet White 750ml Bottle", 
"Cutwater Vodka Mule 4x 12oz Cans", 
"Squirt 12x 12oz Cans", 
"Weller Special Reserve Bourbon 750ml Bottle", 
"The Dalmore 12 Year 750ml Bottle", 
"Corona Refresca Mas Mango Citrus Spiked Tropical Cocktail 24oz Can"]
module.exports = drizlyNames;