const ucNames = ["Crown Royal Fine De Luxe Blended Canadian Whisky (375ml)", 
"Bulleit Bourbon Frontier Whiskey Kentucky Straight Bourbon Whiskey (750ml)", 
"Popov Premium Vodka (375ml)", 
"Popov Premium Vodka (200ml)", 
"Smirnoff No. 57 Blue Label Vodka (750ml)", 
"Smirnoff No. 21 Vodka (750ml)", 
"E&J Extra Smooth Brandy (375ml)", 
"E&J Extra Smooth Brandy (200ml)", 
"E&J Extra Smooth Brandy (1.75L)", 
"E&J Extra Smooth Brandy (750ml)", 
"Bombay Sapphire Distilled London Dry Gin (200ml)", 
"Corona Hard Seltzer Limonada Gluten Free Original Variety Pack Spiked Sparkling Water Cans (12oz x 12x ct)", 
"Cutwater Spirits Cucumber Vodka Soda with Fugu Vodka Cocktail (355ML)", 
"Chivas Regal 18 Yr (750 ml)", 
"Sauza Tres Generaciones Plata (750 ml)", 
"New Amsterdam Straight Gin (1.75 L)", 
"Balvenie 17 Yr Double Wood (750 ml)", 
"Doritos Cool Ranch Flavored Tortilla Chips Bag (9.25oz)", 
"Ciroc Vodka (375 ml)", 
"Ballast Point Big Gus IPA Can (12oz)", 
"Deep Eddy Vodka (750 ml)", 
"Maker's Mark Wood Finishing Series Limited Release Bottle 2019 (750ml)", 
"Maker's Mark 101 Proof Kentucky Straight Bourbon Whiskey (750ml)", 
"Corazon de Agave Reposado Tequila (750ml)", 
"Cheez-It Extra Toasty (12.4 oz)", 
"J & B Rare Blended Scotch Whisky (200ml)", 
"Camarena Tequila Reposado (50 ml)", 
"Topo Chico Hard Seltzer Variety Cans (12oz x 12 ct)", 
"Ernest & Julio Gallo Twin Valley Moscato (750ml)", 
"White Claw Watermelon Cans (12oz x 6 ct)", 
"Hess Cabernet Napa Allomi Vineyard (750 ml)", 
"Carta Blanca Bottle (32oz)", 
"1800 Ultimate Spicy Margarita Bottles (1.75 L)", 
"Pepperwood Grove Pinot Grigio (750ml)", 
"Mr & Mrs T Strawberry Daiquiri Bottles (1 L)", 
"Gfuel Sour Blue Chug Rug Can (16oz)", 
"Estancia Pinot Noir (750 ml)", 
"Tree House Brewing Eureka Blonde Ale Can (16oz)", 
"Snickers Creamy - Peanut Butter Squares (1.4 oz)", 
"Cutwater Cocktails Lime Margarita Cans (12oz x 4 ct)", 
"El Jimador Tequila Reposado (50ml)", 
"Boochcraft Strawberry Lemonade Can 7% ABV (16oz)", 
"Fernet Branca (50 ml)", 
"Mr & Mrs T Bloody Mary Mix Bottles (1 L)", 
"Barefoot Cellars Refresh Sweet White White Wine Blend (750ml)", 
"Cutwater Vodka Mule Cans (12 oz x 4 ct)", 
"Squirt Cans (12oz x 12 ct)", 
"W.L. Weller Special Reserve The Original Wheated Bourbon Kentucky Straight Bourbon Whiskey (750ml)", 
"The Dalmore Single Highland Malt Scotch Whisky 12 Year (750ml)", 
"Corona Refresca Más Mango Citrus Spiked Tropical Cocktail Can (24 oz)"]
module.exports = ucNames;