const ucNames = ["Crown Royal Fine De Luxe Blended Canadian Whisky (375ml)", 
"Bulleit Bourbon Frontier Whiskey Kentucky Straight Bourbon Whiskey (750ml)", 
"Popov Premium Vodka (375ml)", 
"Popov Premium Vodka (200ml)", 
"Smirnoff No. 57 Blue Label Vodka (750ml)", 
"Smirnoff No. 21 Vodka (750ml)", 
"E&J Extra Smooth Brandy (375ml)", 
"E&J Extra Smooth Brandy (200ml)", 
"E&J Extra Smooth Brandy (1.75L)", 
"E&J Extra Smooth Brandy (750ml)", 
"Bombay Sapphire Distilled London Dry Gin (200ml)", 
"Corona Hard Seltzer Limonada Gluten Free Original Variety Pack Spiked Sparkling Water Cans (12oz x 12x ct)", 
"Cutwater Spirits Cucumber Vodka Soda with Fugu Vodka Cocktail (355ML)", 
"Chivas Regal 18 Yr (750 ml)", 
"Sauza Tres Generaciones Plata (750 ml)", 
"New Amsterdam Straight Gin (1.75 L)", 
"Balvenie 17 Yr Double Wood (750 ml)", 
"Doritos Cool Ranch Flavored Tortilla Chips Bag (9.25oz)", 
"Ciroc Vodka (375 ml)", 
"Ballast Point Big Gus IPA Can (12oz)", 
"Deep Eddy Vodka (750 ml)", 
"Maker's Mark Wood Finishing Series Limited Release Bottle 2019 (750ml)", 
"Maker's Mark 101 Proof Kentucky Straight Bourbon Whiskey (750ml)", 
"Corazon de Agave Reposado Tequila (750ml)", 
"Cheez-It Extra Toasty (12.4 oz)", 
"J & B Rare Blended Scotch Whisky (200ml)", 
"Camarena Tequila Reposado (50 ml)", 
"Topo Chico Hard Seltzer Variety Cans (12oz x 12 ct)", 
"Ernest & Julio Gallo Twin Valley Moscato (750ml)", 
"White Claw Watermelon Cans (12oz x 6 ct)", 
"Hess Cabernet Napa Allomi Vineyard (750 ml)", 
"Carta Blanca Bottle (32oz)", 
"1800 Ultimate Spicy Margarita Bottles (1.75 L)", 
"Pepperwood Grove Pinot Grigio (750ml)", 
"Mr & Mrs T Strawberry Daiquiri Bottles (1 L)", 
"Gfuel Sour Blue Chug Rug Can (16oz)", 
"Estancia Pinot Noir (750 ml)", 
"Tree House Brewing Eureka Blonde Ale Can (16oz)", 
"Snickers Creamy - Peanut Butter Squares (1.4 oz)", 
"Cutwater Cocktails Lime Margarita Cans (12oz x 4 ct)", 
"El Jimador Tequila Reposado (50ml)", 
"Boochcraft Strawberry Lemonade Can 7% ABV (16oz)", 
"Fernet Branca (50 ml)", 
"Mr & Mrs T Bloody Mary Mix Bottles (1 L)", 
"Barefoot Cellars Refresh Sweet White White Wine Blend (750ml)", 
"Cutwater Vodka Mule Cans (12 oz x 4 ct)", 
"Squirt Cans (12oz x 12 ct)", 
"W.L. Weller Special Reserve The Original Wheated Bourbon Kentucky Straight Bourbon Whiskey (750ml)", 
"The Dalmore Single Highland Malt Scotch Whisky 12 Year (750ml)", 
"Corona Refresca Más Mango Citrus Spiked Tropical Cocktail Can (24 oz)", 
"Templeton Rye Whiskey (750 ml)", 
"White Claw Hard Seltzer Surge Cranberry Can (16oz)", 
"Red Bull Summer Edition: Watermelon Can (8oz)", 
"Southern Comfort 70 (375 ml)", 
"Cheetos Crunch Pop Mix Bag (2.25oz)", 
"Chex Mix Cheddar (8.75 oz)", 
"Ruffles Flamin' Hot BBQ Flavored Potato Chips Bag (2.5oz)", 
"Red Diamond Chardonnay (750ml)", 
"AriZona Raspberry Tea (23.5oz)", 
"Reese's Peanut Butter Cup Counts (1.5oz x 4x ct)", 
"Cutwater Spirits Grapefruit Vodka Soda with Fugu Vodka Cocktail (355ML)", 
"Doritos Spicy Nacho Bag (9.25oz)", 
"Hess Select Cabernet Sauvignon (750 ml)", 
"Propel Zero Berry Bottle (16.9 oz)", 
"Camarena Tequila Silver (50 ml)", 
"Bud Light Chelada Fuego Can (25oz)", 
"G2 G Series Perform 02 - Glacier Freeze Bottle (20 oz)", 
"White Claw Hard Seltzer Variety Flavor Collection No.3 Cans (12oz x 12 ct)", 
"Ferrari-Carano Fume Blanc (750ml)", 
"Balvenie 12 Yr Double Wood (750 ml)", 
"Southern Comfort 100 (750 ml)", 
"Baken-Ets Hot'n Spicy Flavored Fried Pork Skins Bag (1.5oz)", 
"Casamigos Reposado Tequila (50ml)", 
"Alamos Chardonnay (750ml)", 
"American Harvest Organic Vodka (50ml)", 
"Skyy Infusions Bartlett Pear Vodka (750ml)", 
"Chivas Regal Premium Blended Scotch Whisky 18 Year (50ml)", 
"Chex Mix Bold Party Blend (8.75 oz)", 
"Gatorade G Zero Zero Sugar Thirst Quencher Glacier Cherry Bottle (20 oz)", 
"Michter's US1 Bourbon (750 ml)", 
"Extra Peppermint (1.5 oz)", 
"Fritos Scoops (9.25 oz)", 
"Casamigos Anejo Tequila (50ml)", 
"Crown Royal NFL Jersey Bag (750 ml)", 
"Glenlivet 18 Yr (750 ml)", 
"Raymond Generations Cabernet Sauvignon (750ml)", 
"Maruchan Lime Chili With Shrimp Instant Lunch Ramen Noodle Soup (2.25oz)", 
"ChapStick Classic Spearmint", 
"Tropicana 100% Orange Juice Bottle (52 oz)", 
"Twix Ice Cream Bar (3.13 oz)", 
"Estrella Jalisco/Golden Road Spicy Pina Michelada Can (25oz)", 
"The Macallan Highland Single Malt Scotch Whisky Double Cask 15 Year (750ml)", 
"Snapple Kiwi Strawberry Bottle (16 oz)", 
"Crush Caffeine-Free Strawberry Soda Bottle (20 oz)", 
"Gatorade G Series Thirst Quencher", "Cool Blue Bottle (32oz)", 
"Jagermeister (1.75 L)", 
"Heinz White Vinegar Bottle (16oz)", 
"Skyy Vodka (50 ml)", 
"Einstok Icelandic White Ale Cans (12oz x 6x ct)", 
"Hershey's Cookies'n'Creme King Size", 
"Santa Cristina Pinot Grigio (750ml)", 
"Michelob Ultra Pure Gold & Infusions Light Beer Variety Cans (12 oz x 12 ct)", 
"Coca-Cola Soda Cherry Cans (12 oz x 12 ct)", 
"Earthquake Cabernet (750 ml)", 
"Wild Turkey 101 Kentucky Straight Bourbon Whiskey (50ml)", 
"Glenfiddich 12 Yr (50 ml)", 
"Casamigos Blanco Tequila (50ml)", 
"Herradura Tequila Anejo (50ml)", 
"Dogfish Head 90-Minute IPA Bottles (12oz x 6x ct)", 
"Frito-Lay Sunflower Seeds BBQ (2.125oz)", 
"Bacardi Gold (50 ml)", 
"Rum Chata (750 ml)", 
"Nut Harvest with Almonds", "Cashews", "Pecans", "Pistachios", "and Hazelnuts (2.25 oz)", 
"Fleur de Mer Rose (750 ml)", 
"Hennessy VSOP (375 ml)", 
"Stone Enjoy By 07.04.21 Tangerine & Pineapple IPA Bottle (22oz)", 
"Fritos Flamin' Hot (9.25 oz)", 
"Bud Light Hard Seltzer Out of Office Variety Cans (12 oz x 12 ct)", 
"Truly Hard Seltzer Iced Tea Variety Cans (12oz x 12 ct)", 
"Ultimat Vodka (750ml)", 
"CACTI Pineapple", "Lime & Strawberry Agave Spiked Seltzer Variety Pack Cans (12oz x 9x ct)", 
"S. Pellegrino Essenza Dark Morello Cherry & Pomegranate Can (11.15 oz)", 
"Sutter Home Moscato (187 ml x 4 ct)", 
"Gatorade G Series 02 Perform Frost Glacier Freeze Bottle (20 oz)", 
"Ruffles Queso Cheese (8.5 oz)", 
"Gatorade G Zero Zero Sugar Thirst Quencher Lemon - Lime Bottle (32 oz)", 
"Powerade Strawberry Lemonade Bottle (28oz)", 
"Crush Orange Soda Glass Bottle (12 oz)", 
"Voodoo Ranger American Haze Cans (12oz x 6x ct)", 
"Bacardi Superior (50 ml)", 
"Ciroc Vodka Apple (750 ml)", 
"Sutter Home Merlot (187 ml x 4 ct)", 
"Sazerac Straight Rye Whiskey 6 Year (750ml)", 
"Lay's Kettle Cooked Jalapeno (8 oz)", 
"Apothic Dark Red (750 ml)", 
"Basil Hayden's Dark Rye (750 ml)", 
"Jameson Black Barrel Irish Whiskey (750ml)", 
"Gallo Family Vineyards Merlot (750 ml)", 
"Bushmills (750 ml)", 
"Woodbridge Mondavi Chardonnay (750 ml)", 
"Western Son Vodka (50 ml)", 
"Proper No. Twelve Irish Whiskey (375ml)", 
"Pinnacle Strawberry Shortcake Vodka (750ml)", 
"Old Forester 100 (750 ml)", 
"Menage a Trois Sweet Collection Dolce Red Wine Blend (750ml)", 
"Corona Refresca Variety Pack Bottles (12 oz x 12 ct)", 
"Jekel Vineyards Cabernet Sauvignon (750ml)", 
"Apothic Pinot Noir 2019 (750ml)", 
"Kern River Just Outstanding IPA Cans (16oz x 4x ct)", 
"Act II Light Butter Popcorn Cartons (2.75oz x 3x ct)", 
"Trident Sugarfree Watermelon Gum 14 PC", 
"Barefoot Cellars Cabernet (187 ml x 4 ct)", 
"Apothic Merlot Bottle (750ml)", 
"Planters Unsalted (16 oz)", 
"Modern Times Thundera Hazy IPA 4 pack Cans (16oz)", 
"Johnnie Walker Blue (750 ml)", 
"Firestone Walker 805 Cerveza Pale Lager Can (12oz)", 
"Diet Sprite Zero Bottle (20 oz)", 
"New Amsterdam Pink Whitney (750ml)", 
"Kettle Potato Chips Jalapeno (5oz)", 
"Sour Patch Kids Sour then Sweet (2 oz)", 
"Golden Road Brewing Passion Wolf IPA Cans (12oz x 6x ct)", 
"Luc Belaire Rare Luxe White Wine Blend (750ml)", 
"Monster Pipeline Punch Can (16oz)", 
"The Glenlivet Single Malt Scotch Whisky French Oak Reserve 15 Year (50ml)", 
"J & B Rare Blended Scotch Whisky (50ml)", 
"Attitude Legendary 24 Double Hazy IPA Can (12oz)", 
"Wrigley's Extra Sugarfree Gum Smooth Mint - Long Lasting Flavor 40.5g Box", 
"High West A Midwinter Nights Dram Blended Rye Whiskey (750ml)", 
"Jack Daniels Single Barrel Rye (750 ml)", 
"Kettle Potato Chips Sea Salt & Vinegar (5oz)", 
"Smog City IPA Cans (16oz x 4x ct)", 
"Dos Equis Lager Lime & Salt Pilsner Can (24 oz)", 
"Glen Moray Speyside Single Malt Scotch Whisky 12 Year (750ml)", 
"Puff Bar Banana Ice", 
"3 Musketeers (1.92 oz)", 
"Puff Bar Cool Mint", 
"Hi-Chew Superfruit Chews (3.17oz)", 
"Nature Valley Peanut Butter (1.49 oz)", 
"Jose Cuervo Auth Sparkling Paloma Cans (200 ml x 4 ct)", 
"Platinum Vodka 7X Traveler (1.75 L)", 
"Axxion Foam Plates 22ct", 
"Teremana Tequila Reposado (750ml)", 
"Bacardi Limon (750 ml)", 
"Jose Cuervo Especial Silv Tequila (100 ml)", 
"Newcastle Brown Ale Bottles (12 oz x 12 ct)", 
"19 Crimes Red Blend (750 ml)", 
"Cutwater Spirits Vodka Mule with Fugu Vodka Cocktail (355ML)", 
"Grand Marnier (750 ml)", 
"Corazon de Agave Blanco Tequila (750ml)", 
"Four Roses Single Barrel Bourbon (750 ml)", 
"TRULY Hard Seltzer Strawberry Lemonade", "Spiked & Sparkling Water Cans (12oz x 6x ct)", 
"Stone Neverending Haze IPA Cans (16oz x 4x ct)", 
"Stone Neverending Haze IPA Cans (12oz x 6x ct)", 
"Air Heads White Mystery (0.55 oz)", 
"99 Long Island Iced Tea (50 ml)", 
"Line 39 Cabernet (750 ml)", 
"New Amsterdam Watermelon Vodka (750ml)", 
"The Macallan Fine Oak Highland Single Malt Scotch Whisky 15 Year (750ml)", 
"Martini & Rossi Dry Vermouth (375 ml)", 
"Trident Sugar Free Gum with Xylitol Cinnamon Box (26.6g)", 
"Van Winkle Special Reserve Kentucky Straight Bourbon Whiskey 12 Year (750ml)", 
"Captain Morgan Spiced Rum (50ml)", 
"Tuaca (750 ml)", 
"Body Armor Super Drink Orange Mango Bottle (16 oz)", 
"Donati Family Vineyard Cabernet Sauvignon (750ml)", 
"Air Heads Grape (0.55 oz)", 
"Bell's Official Hazy IPA Cans (16oz x 4x ct)", 
"Stolichnaya Red Label Russian Vodka (200ml)", 
"Twix Cookies & Creme Chocolate Cookie Bar 4 to Go (2.72 oz)", 
"Doritos Spicy Nacho (9.75oz)", 
"Smoking Loon Cabernet (750 ml)", 
"Shock Top Belgian White Ale Bottles (12 oz x 6 ct)", 
"Ballast Point Sculpin IPA Bottles (12 oz x 6 ct)", 
"Black Magic Black Spiced Rum (50 ml)", 
"High Noon Sun Sips Vodka & Soda Pineapple (355ML)", 
"Sauza Hornitos Reposado Tequila (375ml)", 
"Haagen Dazs Ice Cream", "Caramel Cone Pint", 
"Kidsmania Candy Filled Sweet Soaker", 
"Hornitos Reposado Tequila (750 ml)", 
"Sauza 100 Anos Reposado (750 ml)", 
"Sauza Silver Tequila (200ml)", 
"Sauza Blanco Tequila (375ml)", 
"Sauza Silver (750 ml)", 
"Sauza Extra Gold Tequila (200ml)", 
"Sauza Extra Gold Tequila (375ml)", 
"Sauza Gold (750 ml)", 
"Canadian Club (50 ml)", 
"Laphroaig 10 Yr (750 ml)", 
"El Tesoro de Don Felipe Anejo Tequila (750ml)", 
"DeKuyper Hot Damn! Burst Hot Cinnamon Schnapps Liqueur (375ml)", 
"Kessler American Blended Whiskey Traveler (200ml)", 
"Kessler American Blended Whiskey Traveler (375ml)", 
"Jim Beam Black Extra Aged Kentucky Straight Bourbon Whiskey (375ml)", 
"Knob Creek Bourbon (375 ml)", 
"Knob Creek Bourbon (750 ml)", 
"Knob Creek Rye Whiskey (750 ml)", 
"Basil Hayden's Bourbon (750 ml)", 
"Basil Hayden's Bourbon (375 ml)", 
"Jim Beam (50 ml)", 
"Jim Beam (200 ml)", 
"Jim Beam (375 ml)", 
"Jim Beam (750 ml)", 
"Jim Beam (1.75 L)", 
"Saint Pauli Girl Non-Alcoholic Bottles (12 oz x 6 ct)", 
"Victoria Bottles (12 oz x 6 ct)", 
"Modelo Especial Chelada Can (24oz)", 
"Modelo Negra Bottles (12 oz x 6 ct)", 
"Modelo Especial Bottle (24oz)", 
"Modelo Especial Bottles (12 oz x 24 ct)", 
"Modelo Especial Can (24oz x 3 ct)", 
"Modelo Especial Bottles (12 oz x 6 ct)", 
"Modelo Especial Bottles (12 oz x 12 ct)", 
"Modelo Especial Cans (12 oz x 6 ct)", 
"Modelo Especial Can (24oz)", 
"Modelo Especial Cans (12 oz x 12 ct)", 
"Modelo Especial Cans (12 oz x 18 ct)", 
"Modelo Especial Cans (24 oz x 12 ct)", 
"Corona Extra Bottles (12 oz x 12 ct)", 
"Corona Familiar Bottle (32oz)", 
"Corona Extra Bottles (12 oz x 18 ct)", 
"Corona Light Bottles (12 oz x 12 ct)", 
"Corona Extra Can (24oz)", 
"Corona Extra Bottle (24oz)", 
"Corona Light Bottles (12 oz x 6 ct)", 
"Corona Extra Bottles (12 oz x 12 ct)", 
"Corona Extra Bottles (12 oz x 6 ct)", 
"Coronita Bottles (7 oz x 6 ct)", 
"Pacifico Clara Bottles (12 oz x 12 ct)", 
"Pacifico Claro Ballena Bottle (32oz)", 
"Pacifico Clara Bottles (12 oz x 6 ct)", 
"99 Bananas (50 ml)", 
"99 Cinnamon Schnapps Liqueur (50ml)", 
"Chi Chi's Long Island Iced Tea Bottle (187ml)", 
"Chi-Chi’s Original Margarita  Bottle (187ml)", 
"99 Vodka (50ml)", 
"D'Usse Cognac VSOP (200 ml)", 
"N/A", 
"Bombay Sapphire Distilled London Dry Gin (750mL)", 
"Grey Goose (50 ml)", 
"Grey Goose (200 ml)", 
"Grey Goose (375 ml)", 
"Grey Goose Vodka (750ml)", 
"Grey Goose (1.75 L)", 
"Aberfeldy 12 Yr (750 ml)", 
"Cazadores Blanco Tequila (750 ml)", 
"Cazadores Reposado (200ml)", 
"Cazadores Reposado Tequila (50 ml)", 
"Cazadores Reposada Tequila (375 ml)", 
"Cazadores Reposado Tequila (750 ml)", 
"Bacardi Gold (200 ml)", 
"Bacardi Gold (375 ml)", 
"Bacardi Gold (750 ml)", 
"Bacardi Superior (100 ml)", 
"Bacardi Superior (200 ml)", 
"Bacardi Superior (375 ml)", 
"Bacardi Superior (750 ml)", 
"D'Usse Cognac VSOP (375 ml)", 
"D'Usse Cognac VSOP (750 ml)", 
"Jameson Irish Whiskey (1.75 L)", 
"Jameson Irish Whiskey (750 ml)", 
"Jameson Irish Whiskey (375 ml)", 
"Jameson Irish Whiskey (200 ml)", 
"Jameson Irish Whiskey (50 ml)", 
"Seagram's Gin (750 ml)", 
"Seagram's Gin (375 ml)", 
"Seagram's Gin (200 ml)", 
"Martell VS Single Distillery (750 ml)", 
"The Glenlivet Single Malt Scotch Whisky 12 Year (750ml)", 
"Chivas Regal (750 ml)", 
"Chivas Regal Premium Blended Scotch Whisky 12 Year (375ml)", 
"Jameson Cold Brew Whiskey (750ml)", 
"Glenlivet 14 Year Cognac Cask Single Malt Scotch (750ml)", 
"Jameson Caskmates Stout Edition Irish Whiskey (50ml)", 
"Jameson Caskmates Irish Whiskey IPA Edition (50ml)", 
"Martell Blue Swift (750 ml)", 
"Chivas Regal Blended Scotch Whisky (50ml)", 
"Jameson Caskmates Stout Edition (750 ml)", 
"Glenlivet Founder's Reserve (750 ml)", 
"The Glenlivet French Oak Reserve Scotch Whisky 15 Year (750ml)", 
"Columbia Cabernet Sauvignon (750 ml)", 
"Columbia Winery Chardonnay (750ml)", 
"Buffalo Trace Kentucky Straight Bourbon Whiskey (750ml)", 
"Elmer T. Lee Single Barrel Sour Mash Kentucky Straight Bourbon Whiskey (750ml)", 
"Buffalo Trace Bourbon Cream (750 ml)", 
"Blanton's The Original Single Barrel Bourbon Whiskey (750ml)", 
"Kona Big Wave Golden Ale Bottles (12 oz x 6 ct)", 
"Kona Longboard Island Lager Bottles (12 oz x 6 ct)", 
"Menage a Trois Luscious Pinot Noir (750 ml)", 
"Menage a Trois Lavish Merlot (750ml)", 
"Menage a Trois Decadence Cabernet (750 ml)", 
"Menage a Trois Gold Chardonnay (750 ml)", 
"Calypso Lemonade Ocean Blue Bottle (16oz)", 
"Menage a Trois Silk (750 ml)", 
"Menage a Trois Prosecco (750 ml)", 
"Menage a Trois Merlot (750ml)", 
"Menage a Trois Pinot Noir (750 ml)", 
"Menage a Trois Pinot Grigio (750 ml)", 
"Menage a Trois Cabernet (750 ml)", 
"Menage a Trois Chardonnay (750ml)", 
"Bundaberg Peach Sparkling Fruit Drink (12.7 oz)", 
"Menage a Trois Red (750 ml)", 
"Bundaberg Root Beer Bottle (375ml)", 
"Butterfinger (1.9 oz)", 
"Bundaberg Ginger Beer Bottle (12.7oz)", 
"Butterfinger Count (3.7oz)", 
"Michelada Antojitos Drink Mix (24oz)", 
"Evian (1l)", 
"Evian Natural Spring Water 1.5L", 
"Perrier Lime (330ml)", 
"Wonka Sweet Tarts Giant Chewy (1.5 oz)", 
"El Sabroso Hot & Spicy Pork Cracklins (1.625 oz)", 
"El Sabroso Pork Cracklins (2.25 oz)", 
"El Sabroso Jalapenitos 3 Cheese & Jalapeno (3 oz)", 
"El Sabroso Salsitas Spicy Salsa Tortilla Rounds (3 oz)", 
"El Sabroso Guacachip Guacamole (3 oz)", 
"Lenny & Larry's The Complete Cookie - White Chocolate Macadamia (4 oz)", 
"Lenny & Larry's The Complete Cookie - Snickerdoodle (4 oz)", 
"Lenny & Larry's The Complete Cookie - Double Chocolate (4 oz)", 
"Lenny & Larry's The Complete Cookie - Oatmeal Raisin (4 oz)", 
"Lenny & Larry's The Complete Cookie - Chocolate Chip (4 oz)", ]
module.exports = ucNames;